services:
  app:
    image: php:8.3-fpm
    container_name: oldskool_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src/:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - oldskool

  webserver:
    image: nginx:alpine
    container_name: oldskool_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - oldskool
    depends_on:
      - app

  db:
    image: mariadb:latest
    container_name: oldskool_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - oldskool

networks:
  oldskool:
    driver: bridge
